FollowTheFleet/Controllers/CarController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using FollowTheFleet.Model;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FollowTheFleet.Controllers
{
    [RequireHttps]
    public class CarController : Controller
    {
        private readonly ICarRepository _carRepository;
        private IHostingEnvironment _env;

        public CarController(ICarRepository carRepository, IHostingEnvironment env)
        {
            _carRepository = carRepository;
            _env = env;
        }

        public IActionResult Details(int id)
        {
            var car = _carRepository.GetSingleCar(id);
            if (car == null)
                return NotFound();
            return View(car);
        }

        public IActionResult Create(string FileName)
        {
            if (!string.IsNullOrEmpty(FileName))
                ViewBag.ImgPath = "/Images/" + FileName;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Car car)
        {
            if (ModelState.IsValid)
            {
                _carRepository.AddCar(car);
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        public IActionResult Edit(int id, string FileName)
        {
            var car = _carRepository.GetSingleCar(id);
            if (car == null)
                return NotFound();

            if (!string.IsNullOrEmpty(FileName))
                ViewBag.ImgPath = "/Images/" + FileName;
            else
                ViewBag.ImgPath = car.PhotoUrl;

            return View(car);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Car car)
        {
            if (ModelState.IsValid)
            {
                _carRepository.EditCar(car);
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        public IActionResult Delete(int id)
        {
            var car = _carRepository.GetSingleCar(id);
            if (car == null)
                return NotFound();
            return View(car);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id, string photoUrl)
        {
            var car = _carRepository.GetSingleCar(id);
            _carRepository.DeleteCar(car);

            if(photoUrl != null)
            {
                var webRoot = _env.WebRootPath;
                var filePath = Path.Combine(webRoot.ToString() + photoUrl);

                System.IO.File.Delete(filePath);
            }


            return RedirectToAction(nameof(Index));
        }

        [HttpPost("UploadFile")]
        public async Task<IActionResult> UploadFile(IFormCollection form)
        {
            var webRoot = _env.WebRootPath;
            var filePath = Path.Combine(webRoot.ToString() + "\\images\\" + form.Files[0].FileName);

            if (form.Files[0].FileName.Length > 0)
            {
                using(var stream = new FileStream(filePath, FileMode.Create))
                {
                    await form.Files[0].CopyToAsync(stream);
                }
            }
            if (Convert.ToString(form[""]) == string.Empty || Convert.ToString(form[""]) == "0")
                return RedirectToAction(nameof(Create), new { FileName = Convert.ToString(form.Files[0].FileName) });
            return RedirectToAction(nameof(Edit), new { FileName = Convert.ToString(form.Files[0].FileName), id = Convert.ToString(form["Id"]) });
        }

        public async Task<IActionResult> Index(string searchString)
        {
            var cars = from m in _carRepository.GetAllCars()
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                cars = cars.Where(s => s.Brand.Contains(searchString));
            }

            return View(await Task.FromResult(cars.ToList()));
        }

        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }
    }
}

FollowTheFleet/Views/Car/Create.cshtml
@model Car

<h2>Dodaj Samochod</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-action="UploadFile">
            <div class="form-group">
                <input type="hidden" asp-for="Id"/>
                <label class="control-label">Zdjęcie samochodu</label><br/>
                <img src="@ViewBag.ImgPath" height="300" width="300"/><br/>
                <input type="file" name="file" style="margin-top:10px"/>
            </div>
            <div class="form-group">
                <input type="submit" value="Załaduj zdjęcie" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div class="row">
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Brand" class="control-label">Marka</label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label">Typ</label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearOfProduction" class="control-label">Rok Produkcji</label>
                <input asp-for="YearOfProduction" class="form-control" />
                <span asp-validation-for="YearOfProduction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mileage" class="control-label">Przebieg</label>
                <input asp-for="Mileage" class="form-control" />
                <span asp-validation-for="Mileage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Insurance" class="control-label">Ubezpieczenie?</label>
                <input asp-for="Insurance" class="form-control" />
                <span asp-validation-for="Insurance" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="ServiceDate" class="control-label">Data ostatniego przeglądu</label>
                <input asp-for="ServiceDate" class="form-control" />
                <span asp-validation-for="ServiceDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Owner" class="control-label">Właściciel</label>
                <input asp-for="Owner" class="form-control" />
                <span asp-validation-for="Owner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LicensePlate" class="control-label">Właściciel</label>
                <input asp-for="LicensePlate" class="form-control" />
                <span asp-validation-for="LicensePlate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Opis</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="PhotoUrl" value="@ViewBag.ImgPath" />
            <input type="hidden" asp-for="ThumbnailUrl" value="@ViewBag.ImgPath" />
            <div class="form-group">
                <input type="submit" value="Dodaj samochód" class="btn btn-success" style="margin-top:30px" />
                <a asp-action="Index" class="btn btn-danger pull-right" style="margin-top:30px">Powrót</a>
            </div>
        </div>
    </form>
</div>

FollowTheFleet/Views/Car/Delete.cshtml
@model Car
<div>
    <div class="thumbnail">
        <div class="row">
            <div class="col-md-6">
                <img alt="@Model.Brand" src="@Model.PhotoUrl" height="500" width="500" />
            </div>
            <div class="col-md-6">
                <h3>@Model.Brand - @Model.Type</h3>
                <h4>@Model.Owner</h4>
                <h4>@Model.YearOfProduction</h4>
                <h4>@Model.Capacity</h4>
                <h4>@Model.Mileage</h4>
                <h4>@Model.ServiceDate</h4>
                <p>@Model.Description</p>
                <h2>Na pewno chcesz usunąć?</h2>
                <h4 class="pull-right">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="hidden" asp-for="PhotoUrl"/>
                        <input type="submit" value="Usuń" class="btn btn-success" />
                        <a asp-action="Index" class="btn btn-success">Powrót</a>
                    </form>
                </h4>
            </div>
        </div>
    </div>
</div>

FollowTheFleet/Views/Car/Details.cshtml
@model Car

<div>
    <div class="thumbnail">
        <div class="row">
            <div class="col-md-6">
                <img alt="@Model.Brand" src="@Model.PhotoUrl" height="500" width="500" />
            </div>
            <div class="col-md-3">
                <h3>@Model.Brand - @Model.Type</h3>
                <h4>@Model.YearOfProduction</h4>
                <h4>@Model.Mileage</h4>
                <h4>@Model.Owner</h4>
                <h4>@Model.Insurance</h4>
                <h4>@Model.ServiceDate</h4>
                <h4>@Model.LicensePlate</h4>
                <p>@Model.Description</p>
            </div>
            <div class="col-md-3" style="padding-right:50px">
                <h3 class="pull-right">
                    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-success">Edycja</a>
                    <a asp-action="Index" class="btn btn-success">Powrót</a>
                </h3>
            </div>
        </div>
    </div>
</div>

FollowTheFleet/Views/Car/Edit.cshtml
@model Car

<h2>Edytuj Samochod</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-action="UploadFile">
            <div class="form-group">
                <input type="hidden" asp-for="Id" />
                <label class="control-label">Zdjęcie samochodu</label><br />
                <img src="@ViewBag.ImgPath" height="300" width="300" /><br />
                <input type="file" name="file" style="margin-top:10px" />
            </div>
            <div class="form-group">
                <input type="submit" value="Załaduj zdjęcie" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="row">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Brand" class="control-label">Marka</label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label">Typ</label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearOfProduction" class="control-label">Rok Produkcji</label>
                <input asp-for="YearOfProduction" class="form-control" />
                <span asp-validation-for="YearOfProduction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mileage" class="control-label">Przebieg</label>
                <input asp-for="Mileage" class="form-control" />
                <span asp-validation-for="Mileage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Insurance" class="control-label">Ubezpieczenie?</label>
                <input asp-for="Insurance" class="form-control" />
                <span asp-validation-for="Insurance" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="ServiceDate" class="control-label">Data ostatniego przeglądu</label>
                <input asp-for="ServiceDate" class="form-control" />
                <span asp-validation-for="ServiceDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Owner" class="control-label">Właściciel</label>
                <input asp-for="Owner" class="form-control" />
                <span asp-validation-for="Owner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Opis</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="PhotoUrl" value="@ViewBag.ImgPath" />
            <input type="hidden" asp-for="ThumbnailUrl" value="@ViewBag.ImgPath" />
            <div class="form-group">
                <input type="submit" value="Zapisz edycje" class="btn btn-success" style="margin-top:30px" />
                <a asp-action="Index" class="btn btn-danger pull-right" style="margin-top:30px">Powrót</a>
            </div>
        </div>
    </form>
</div>

FollowTheFleet/Views/Car/Index.cshtml
@model IEnumerable<Car>

<form asp-controller="Car" asp-action="Index" method="get">
    <p>
        <input type="text" name="searchString">
        <input type="submit" class="btn btn-success btn-sm" style="margin-bottom:3px" value="Szukaj" />
    </p>
</form>

<table class="table" style="background-color:azure">
<thead>
    <tr>
        <th>Marka</th>
        <th>Typ</th>
        <th>Rok</th>
        <th>Przebieg</th>
        <th>Numer rejestracyjny</th>
        <th>Właściciel</th>
        <th>Ubezpieczenie</th>
        <th>Data przeglądu</th>
        <th>Opis</th>
        <th>
            <a asp-action="Create" class="btn btn-danger btn-sm">Dodaj nowy</a>
        </th>
    </tr>
</thead>
<tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Brand)</td>
            <td>@Html.DisplayFor(modelItem => item.Type)</td>
            <td>@Html.DisplayFor(modelItem => item.YearOfProduction)</td>
            <td>@Html.DisplayFor(modelItem => item.Mileage)</td>
            <td>@Html.DisplayFor(modelItem => item.LicensePlate)</td>
            <td>@Html.DisplayFor(modelItem => item.Owner)</td>
            <td>@Html.DisplayFor(modelItem => item.Insurance)</td>
            <td>@Html.DisplayFor(modelItem => item.ServiceDate)</td>
            <td>@Html.DisplayFor(modelItem => item.Description)</td>
            <td><img src="@item.ThumbnailUrl" height="100" width="100" /></td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-success btn-sm" style="margin-bottom:3px">Szczegóły</a>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success btn-sm" style="margin-bottom:3px">Edytuj</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-success btn-sm" style="margin-bottom:3px">Usuń</a>
            </td>
        </tr>
    }
</tbody>
</table>